definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterRequest:
    properties:
      confirmation_password:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - confirmation_password
    - email
    - password
    type: object
  auth.Response:
    type: object
  common.Response:
    properties:
      code:
        format: json
      message:
        format: string
        type: string
      status:
        format: string
        type: string
    type: object
  post_service.postCreateRequest:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - description
    - title
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logins when you provide details
      parameters:
      - description: Parameters should not be empty
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Response'
      summary: Authenticates when provided with login details
  /posts:
    post:
      consumes:
      - application/json
      parameters:
      - description: Parameters should not be empty
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/post_service.postCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: Creates post
  /register:
    post:
      consumes:
      - application/json
      description: Registers when you provide details
      parameters:
      - description: Parameters should not be empty
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Response'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.Response'
      summary: Registers a user when provided with details
swagger: "2.0"
